# Generated by Django 5.1.1 on 2024-09-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='domain',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
