# Generated by Django 5.1.1 on 2024-09-09 01:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('card', 'Card'), ('cash', 'Cash on delivery')], default='cash')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('successful', 'Successful')], default='pending')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('digital_transaction_id', models.CharField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='order.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
